### ISSUE TITLE
port for gogs

### ISSUE THREAD

**Issue by morph027** [drone-plugins/drone-github-release#13] opened 2016-03-12 17:14 UTC
I'm fairly new to drone and just started playing around with gogs. As drone has support for gogs as remote driver, it would be cool to support the release feature of gogs too (in a different plugin of course) ...

**Comment by tboerger** [comment] 2016-03-14 08:33
New plugins are always welcome. If you have written a new plugin and you want to publish it as an official plugin just show it to us on the [gitter chat](https://gitter.im/drone/drone-dev) or post it on [our discussion site](https://discuss.drone.io/), than we can review it and create a repository for that.

I will close this issue for now as it's not realted to this and it's not a bug. For the future please use the discussion site or the gitte chat for this kind of request. Thanks!

**Closed by tboerger** 2016-03-14 08:33 UTC
